version: '2'
services:
  database:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: migu_test
      MYSQL_PASSWORD: xue7AO3p!
      MYSQL_DATABASE: migu_test
